### ISSUE TITLE
python3 train_model.py报错

### ISSUE THREAD

**Issue by Jamin2018** [nickliqian/cnn_captcha#104]
如下
(base) MBP:cnn_captcha-master jamin$ python3 train_model.py
Traceback (most recent call last):
  File "train_model.py", line 275, in <module>
    main()
  File "train_model.py", line 269, in main
    image_suffix, train_batch_size, test_batch_size, verify=False)
  File "train_model.py", line 60, in __init__
    super(TrainModel, self).__init__(image_height, image_width, len(label), char_set, model_save_dir)
  File "/Users/jamin/PycharmProjects/finance/cnn_captcha-master/cnnlib/network.py", line 22, in __init__
    self.X = tf.placeholder(tf.float32, [None, self.image_height * self.image_width])  # 特征向量
AttributeError: module 'tensorflow' has no attribute 'placeholder'

**Comment by zyh001** [comment]
@Jamin2018 你的`TensorFlow`版本是什么？

**Comment by Jamin2018** [comment]
> @Jamin2018 你的`TensorFlow`版本是什么？

应该是最新的

**Comment by zyh001** [comment]
> > @Jamin2018 你的`TensorFlow`版本是什么？
> 
> 应该是最新的

你应该是用的`tf 2.x`，降级成`tf 1.x`就行，或者修改代码，将
````
import tensorflow as tf
````
替换为
````
import tensorflow.compat.v1 as tf
tf.disable_v2_behavior()
````
就行

**Comment by Jamin2018** [comment]
感谢------------------ 原始邮件 ------------------
发件人: "stack zhao"<notifications@github.com>
发送时间: 2019年11月7日(星期四) 晚上10:43
收件人: "nickliqian/cnn_captcha"<cnn_captcha@noreply.github.com>;
抄送: "Jamin2018"<389098898@qq.com>;"Mention"<mention@noreply.github.com>;
主题: Re: [nickliqian/cnn_captcha] python3 train_model.py报错 (#104)


  
@Jamin2018 你的TensorFlow版本是什么？
  
应该是最新的
  
你应该是用的tf 2.x，降级成tf 1.x就行，或者修改代码，将
 import tensorflow as tf  
替换为
 import tensorflow.compat.v1 as tf tf.disable_v2_behavior()  
就行
 
&mdash;

**Comment by zhihuiyuze** [comment]
我修复了下这个问题
https://github.com/zhihuiyuze/cnn_captcha
