### ISSUE TITLE
训练集准确率

### ISSUE THREAD

**Issue by amandaYYY** [nickliqian/cnn_captcha#12]
结果：训练集和验证集正确率相差太远是为什么，log如下：）
第10次训练 >>> [训练集] 准确率为 0.9674999713897705 >>> loss 0.01326522696763277
            >>> [验证集] 准确率为 0.17000000178813934 >>> loss 0.01326522696763277
第20次训练 >>> [训练集] 准确率为 1.0 >>> loss 0.005544836632907391
            >>> [验证集] 准确率为 0.23000000417232513 >>> loss 0.005544836632907391
第30次训练 >>> [训练集] 准确率为 0.9375 >>> loss 0.0032186058815568686
            >>> [验证集] 准确率为 0.19249999523162842 >>> loss 0.0032186058815568686
步骤：
（1.训练集的图片原来有1000张，开始使用train_model.py进行训练集识别，7000多次训练 准确率依然在15%左右转动，所以人为停止了训练，此过程从未进行过test_batch.py验证测试集；
   2. 将训练集图片减少到600张，使用train_model2.py开始训练，就出现了log中所示。PS:进行第二步时，第一步骤产生的模型文件未删除）

**Comment by nickliqian** [comment]
@amandaYYY 
这是模型的泛化能力不强的问题，训练集正确率高说明模型把训练集的特征都学到了。
对验证集来说模型是没有学习过从，所以很多特征是模型无法辨认的，因此正确率低。
可以考虑增加负样本训练用来提升验证集的准确率。
