### ISSUE TITLE
ValueError: 'o' is not in list

### ISSUE THREAD

**Issue by Easul** [nickliqian/cnn_captcha#128]
如果碰到本标题的问题,是因为准备的验证码中的标签有在conf/sample_config的char_set中没有列举出来的字符出现.我的验证码是自己手动打的标签,所以有时候会有错误,就像这个提示是小写的'o'没有在字符集里.所以需要去修改一下标签或者在char_set中加入没有加入的字符.我的验证码里不需要'o'这个字符,纯属是我自己做标注的时候手误,只需要改一下验证码标签即可

**Comment by qwehua-github** [comment]
老哥,没太明白.我获取了一堆图片验证码,都是4位纯数字,提示我的是ValueError:'p' is not in list

**Comment by Easul** [comment]
你看看你的验证码的标签里是不是有p这个字符，这个错误就是标签里有p，但是charset里没填。如果是纯数字的验证码，标签里应该只有数字才对。我的情况是我自己手动给验证码打的标签，但是手误打错了，charset也没有这个字符，所以报错
