### ISSUE TITLE
recognize_api越跑越慢

### ISSUE THREAD

**Issue by yangxiangguo** [nickliqian/cnn_captcha#14]
由于不太懂python，但是代码成功跑起来了 ，刚开始识别图片响应时间在ms级别，然后一直缓慢下来，大概运行到2万次请求，响应时间到了2s左右

**Comment by nickliqian** [comment]
@yangxiangguo 
已经优化，pull最新代码即可使用。
原因是在迭代过程中，tensorflow的计算每次都会创建一个张量，导致内存溢出。
更新代码后可以使用`recognize_time_test.py`脚本进行压力测试统计请求数据。
