### ISSUE TITLE
生成样本得算法怎么样

### ISSUE THREAD

**Issue by mengpengfei** [nickliqian/cnn_captcha#15]
生成样本得算法怎么样，生成得验证码训练后能应付网上得那些验证码吗

**Comment by nickliqian** [comment]
生成的样本只能识别跟样本类型类似的验证码。
如果要能应付大部分验证码需要大量的样本进行训练才行（百万到上千万）

**Comment by mengpengfei** [comment]
只要能用，生成上千万的验证码没问题
