### ISSUE TITLE
调用接口上传图片到webserver 时间很长

### ISSUE THREAD

**Issue by amandaYYY** [nickliqian/cnn_captcha#19]
环境：启动了两个api server,并且使用nginx进行了负载均衡，

现象：用jmeter模拟接口http://127.0.0.1:6000/b 上传图片到Webserver时（jmeter只启动一个线程），发现 
           经常长时间的未上传到服务器；
          jmeter运行20分钟才上传50次左右的请求，这是什么原因老是卡在上传过程呢？

**Comment by nickliqian** [comment]
请检查如下因素：
1. 是否对recognize_api.py和recognition_object.py的配置做一些修改？
2. 是否有最新版的recognize_api.py和recognition_object.py？（2018.12.08针对性能问题作了一次优化）
3. 图片尺寸和大小多大？
4. 是否存在网络链接问题？
关于请求速度，可以参考readme.md的压力测试部分。
