### ISSUE TITLE
自己生成图片训练，acc 一直是0.1左右

### ISSUE THREAD

**Issue by jewelcai** [nickliqian/cnn_captcha#27]
自己生成图片训练，acc 一直是0.1左右，不知道问题出在哪了，是不是数据的原因？

第160次训练 >>> 
[训练集] 字符准确率为 0.10000 图片准确率为 0.00000 >>> loss 0.1013903320
[验证集] 字符准确率为 0.10750 图片准确率为 0.00000 >>> loss 0.1013903320
第170次训练 >>> 
[训练集] 字符准确率为 0.12750 图片准确率为 0.00000 >>> loss 0.1000958011
[验证集] 字符准确率为 0.08500 图片准确率为 0.00000 >>> loss 0.1000958011
第180次训练 >>> 
[训练集] 字符准确率为 0.12750 图片准确率为 0.00000 >>> loss 0.0998161957
[验证集] 字符准确率为 0.11250 图片准确率为 0.00000 >>> loss 0.0998161957
第190次训练 >>> 
[训练集] 字符准确率为 0.12750 图片准确率为 0.00000 >>> loss 0.0985096842
[验证集] 字符准确率为 0.10750 图片准确率为 0.00000 >>> loss 0.0985096842
第200次训练 >>> 
[训练集] 字符准确率为 0.10000 图片准确率为 0.00000 >>> loss 0.0990609303
[验证集] 字符准确率为 0.08000 图片准确率为 0.00000 >>> loss 0.0990609303
第210次训练 >>> 
[训练集] 字符准确率为 0.13000 图片准确率为 0.00000 >>> loss 0.1007201374
[验证集] 字符准确率为 0.07250 图片准确率为 0.00000 >>> loss 0.1007201374
第220次训练 >>> 
[训练集] 字符准确率为 0.13750 图片准确率为 0.00000 >>> loss 0.0987524837
[验证集] 字符准确率为 0.10250 图片准确率为 0.00000 >>> loss 0.0987524837
第230次训练 >>> 
[训练集] 字符准确率为 0.10000 图片准确率为 0.00000 >>> loss 0.0986539647
[验证集] 字符准确率为 0.06500 图片准确率为 0.00000 >>> loss 0.0986539647
第240次训练 >>> 
[训练集] 字符准确率为 0.10750 图片准确率为 0.00000 >>> loss 0.0977340937
[验证集] 字符准确率为 0.08750 图片准确率为 0.00000 >>> loss 0.0977340937
第250次训练 >>> 
[训练集] 字符准确率为 0.12500 图片准确率为 0.00000 >>> loss 0.0980810747
[验证集] 字符准确率为 0.10250 图片准确率为 0.00000 >>> loss 0.0980810747
第260次训练 >>> 
[训练集] 字符准确率为 0.10000 图片准确率为 0.00000 >>> loss 0.0975745544
[验证集] 字符准确率为 0.05250 图片准确率为 0.00000 >>> loss 0.0975745544
第270次训练 >>> 
[训练集] 字符准确率为 0.12750 图片准确率为 0.00000 >>> loss 0.0960663259
[验证集] 字符准确率为 0.10750 图片准确率为 0.00000 >>> loss 0.0960663259

`    root_dir = "../sample/python_captcha/"  # 图片储存路径
    image_suffix = "png"  # 图片储存后缀
    characters = "0123456789"  # 图片上显示的字符集
    # characters = "0123456789abcdefghijklmnopqrstuvwxyz"
    count = 1000  # 生成多少张样本
    char_count = 4  # 图片上的字符数量`

`# 验证码字符相关参数
sample_conf.char_set = ['0', '1', '2', '3', '4', '5', '6', '7', '8', '9']`

**Comment by nickliqian** [comment]
@jewelcai 训练到3000轮左右看一下准确率呢？
