### ISSUE TITLE
能识别复杂的验证码吗？

### ISSUE THREAD

**Issue by wylc** [nickliqian/cnn_captcha#28]
能识别复杂的验证码吗？比如
![10](https://user-images.githubusercontent.com/16163015/53546418-3c3fdf80-3b67-11e9-872f-cd0176fe583f.png)
![0a5j_5032e7fcaceb4dbca5ad9a967610adaa](https://user-images.githubusercontent.com/16163015/53546435-4a8dfb80-3b67-11e9-8f1e-a0cd05076335.jpg)

**Comment by nickliqian** [comment]
使用相应的样本训练即可。

**Comment by wylc** [comment]
如果我训练了一批验证码，准确率达到了99%，然后我替换掉训练集和测试集验证码再次进行训练，再次达到99%,我再用两次训练后的模型来测试第一次的测试集的验证码，还能达到99%吗，两次训练是不同的验证码生成器生成的不同验证码。

**Comment by nickliqian** [comment]
@wylc 可能和99%差不了太多，不过建议把所有的训练集放在一起进行训练

**Comment by wylc** [comment]
牛，我试试
