### ISSUE TITLE
字符准确率和图片准确率？

### ISSUE THREAD

**Issue by fishmisswater** [nickliqian/cnn_captcha#29]
字符准确率：
acc_char = sess.run(accuracy_char_count, feed_dict={self.X: batch_x_verify, self.Y: batch_y_verify, self.keep_prob: 1.})
图片准确率：
acc_image = sess.run(accuracy_image_count, feed_dict={self.X: batch_x_verify, self.Y: batch_y_verify, self.keep_prob: 1.})
啥是字符准确率？字符准确率和图片准确率的区别是什么？

**Comment by nickliqian** [comment]
可以参考一下这个呢
#16
