### ISSUE TITLE
训练的时候报错

### ISSUE THREAD

**Issue by mxm145** [nickliqian/cnn_captcha#3]
在用测试集进行训练的时候报错了，是要在model文件夹下面放现成的模型吗？
![image](https://user-images.githubusercontent.com/869702/48762155-6589dd80-ece5-11e8-82bc-a76fc3665fea.png)
不好意思是新手，直接跑的代码

**Comment by nickliqian** [comment]
@mxm145 不用现成的model，这应该是一个bug：检测到存在model目录就认为有旧的模型，会执行restore操作从而报错。
加入了异常处理，已经修复。
