### ISSUE TITLE
能否自己调整训练集跟验证集集的数量

### ISSUE THREAD

**Issue by MikuShare** [nickliqian/cnn_captcha#32]
你好，我这边用了10w张生成的验证码训练。使用GPU，大概在一小时左右把训练集正确率训练到了百分百，但是验证集集这里的准确率还在40-50%左右。途中遇到了几个问题：
1.训练的时候，每3000轮就会停下，需要手动等3000轮完成再运行。这次训练了接近几万轮，基本都是每3000轮就要自己动一下，能不能一下直接训练完成。
2.在数字，小写字母，大写字母都存在的情况下，使用单单1000张验证码完全不能起到训练泛模型的作用，所以我想能不能自己把训练集跟验证集调整为一样，然后只对这一千字进行训练识别，虽然这样只能作用于这一千张验证码，但是我想试一下。
3.如果想达到95%以上的正确率，是否千万张图片是必须的。
4.我在readme跟别的issues都看到你说了：增加负样本训练来提升准确率，请问这个需要怎么实现。

**Comment by MikuShare** [comment]
![image](https://user-images.githubusercontent.com/25380989/55047862-2ac3f780-5081-11e9-8d52-c58b83321486.png)
十万张的准确率在50%以下，一万张在1%以下，一万张以下的话准确率为0.

**Comment by nickliqian** [comment]
@MikuShare 你好，非常感谢反馈！
1. 目前停止训练的条件有两个：a.训练3000轮 b.准确率达到99%。目前不支持配置化，可以在 https://github.com/nickliqian/cnn_captcha/blob/master/train_model_v2.py#L251 位置修改训练的循环次数。后续会加入停止条件配置化。
2. 调整训练集和验证集，可以直接把你想要训练和验证的图片替换到如下路径，然后开始训练即可
```
sample_conf.train_image_dir = "./sample/train/"
sample_conf.test_image_dir = "./sample/test/"
```
3. 按照生成图片验证码训练得到的模型准确率，我这边大概2W张图片验证集准确率可以达到70%左右，至于你那边10w张50%，你是数字，小写字母，大写字母都存在的情况吗？我有空会测试一下。
4. 增加负样本，就是把你训练好的模型，拿去识别新的图片，把错误的图片标记正确放到训练集中去让模型继续学习。

**Comment by MikuShare** [comment]
@nickliqian 谢谢指导，我先按照你说的来。
1.我先把循环修改成10w
2.完成拷贝后，这两个文件夹目前验证码是一样的。
3.我是数字，小写字母，大写字母都存在的情况下训练的。
4.关于：增加负样本，就是把你训练好的模型，拿去识别新的图片，把错误的图片标记正确放到训练集中去让模型继续学习。
这样的操作是要手动一个个来吗？

**Comment by nickliqian** [comment]
第四点，就是标记负样本，途径有：
1. 手动标记
2. 花钱买接口标记识别
3. 我训练了一个通用识别接口，晚上你有空发邮件我，给你免费识别负样本
4. 增加样本量

**Comment by MikuShare** [comment]
@nickliqian 十分感谢，我的邮箱：aurelius.l@qq.com
那把错误的图片标记正确放到训练集中去，这一步操作是脚本完成还是也手动操作。

**Comment by MikuShare** [comment]
你好，以上问题基本搞清楚也解决了。现在遇到了这个问题：
1.我使用Java的patchca生成了5w个验证码为：
![image](https://user-images.githubusercontent.com/25380989/55157645-ed05c280-5197-11e9-8eb4-78a8bb0821f8.png)
训练完成后，准确率很高，再用patchca生成之后的验证码识别基本都能通过。
但是使用百度的验证码为：
![image](https://user-images.githubusercontent.com/25380989/55157727-1888ad00-5198-11e9-9881-5fe96a802abb.png)
感觉类型差别基本不是很大，但是正确率为0，请问现在这种情况是怎么办呢？

**Comment by nickliqian** [comment]
@MikuShare 
需要使用这种类型的验证码进行训练才行。  
使用单一验证码样本集训练出来的模型泛化能力是很差的，哪怕只是大小或者倾斜角度差一点点可能都会导致准确率很低。

**Comment by MikuShare** [comment]
@nickliqian 
原来如此，我现在是这样操作的：
先对十万张百度的验证码使用打码平台来识别。
将识别并且标记后的图片放入origin文件夹，然后依次运行程序。
当训练完成之后，准确率有70%以上了，我用来识别新的验证码，然后手动来给识别好的验证码做区分。
把识别错误的手动修改成正确的标识后，把以前的训练集删除(因为这个训练集里有蛮多错误的)，把负样本放入训练集使用训练好的模型继续训练。
你看这样可以么？
把以前的训练集删除是因为以前的训练集里有错误的样本，所以删除以免继续错误。

**Comment by nickliqian** [comment]
流程是可以的。如果错误的不是太多，不删除也是可以的。
给你发了一封邮件，是我目前开发的一个比较通用的验证码OCR API，可以试一下。

**Comment by MikuShare** [comment]
好的，感谢指导。收到了邮件，再次表示感谢！
