### ISSUE TITLE
使用gpu加速的话gpu内存不足

### ISSUE THREAD

**Issue by asjdf** [nickliqian/cnn_captcha#34]
除了更改显卡以外还有其他解决方式吗?

**Comment by asjdf** [comment]
emmm 想问一下2g显存跑得动吗 我好像意识到问题不是出在显存上

**Comment by asjdf** [comment]
3000次后准确率没有提高多少（0.1多） 只有lose降低了一些
是因为验证码比较不好学习需要增加学习的次数吗

**Comment by nickliqian** [comment]
@asjdf 可以贴出你的验证码，还有具体的日志
