### ISSUE TITLE
关于中文识别

### ISSUE THREAD

**Issue by billycn** [nickliqian/cnn_captcha#36]
你好，测试了一下中文识别。3600个字，10W张标注好的单字图片。学习很快，99%停止。测试时基本上50%的识别率，请问这个该如何提高识别率呢。

**Comment by billycn** [comment]
通过增加学习次数，增加负向样本，提高了些

**Comment by nickliqian** [comment]
1. 增加学习次数
2. 增加负样本进行训练
3. 图像前处理
4. 数据增强
5. 调参
6. 训练集错误数据修复
