### ISSUE TITLE
验证码图片大小不一样能训练吗

### ISSUE THREAD

**Issue by koalang** [nickliqian/cnn_captcha#38]
验证码是算术题 两位以内整数相加
一位跟两位的整数相加的验证码大小不一样
![_1555219778886](https://user-images.githubusercontent.com/23659068/56088781-060db380-5eba-11e9-9984-ec610752a475.png)
![_1555219779938](https://user-images.githubusercontent.com/23659068/56088783-0ad26780-5eba-11e9-867e-e567e78c7cb7.png)
![_1555219817008](https://user-images.githubusercontent.com/23659068/56088784-0e65ee80-5eba-11e9-9485-68d2f416a6d3.png)

**Comment by nickliqian** [comment]
本项目暂时不支持验证码图片大小不一样的样本训练。
