### ISSUE TITLE
python3 verify_and_split_data.py error

### ISSUE THREAD

**Issue by 1225358814** [nickliqian/cnn_captcha#4]
Mac OS 10.13.4
python3.6
cat ~/.matplotlib/matplotlibrc
backend: TkAgg

sample_conf.image_width = 200
sample_conf.image_height = 50
sample_conf.max_captcha = 5
sample_conf.remote_url = "https://www.epubit.com/kaptcha.jpg?v=0.24931664260119102"

train 149
test 7

-->使用测试集为 ./sample/train/
>>> Start model test
0:100
Traceback (most recent call last):
  File "train_model.py", line 251, in <module>
    main()
  File "train_model.py", line 245, in main
    tm = TrainModel(train_image_dir, char_set, model_save_dir)
  File "train_model.py", line 56, in __init__
    batch_x, batch_y = self.get_batch(0, size=100)
  File "train_model.py", line 120, in get_batch
    batch_y[i, :] = self.text2vec(label)  # 生成 oneHot
  File "train_model.py", line 100, in text2vec
    idx = i * self.char_set_len + self.char_set.index(ch)
ValueError: ' ' is not in list

**Comment by 1225358814** [comment]
while I change file
tran_model.py:190-193
`            # 恢复模型
            # if os.path.exists(self.model_save_dir):
            #     saver.restore(sess, self.model_save_dir)
            # else:
            #     pass`
that train process running
but a minute a after 

` File "/Users/this/.local/share/virtualenvs/cnn_captcha-iurAiuUC/lib/python3.6/site-packages/PIL/Image.py", line 2657, in open
    % (filename if filename else fp))
OSError: cannot identify image file './sample/train/.DS_Store'`

think that is Mac OS system problem 
I well deal that re try

**Comment by 1225358814** [comment]
第160次训练 >>> 准确率为 0.03200000151991844 >>> loss 0.1337910294532776

**Comment by nickliqian** [comment]
thanks!
I will review your PR and fix this bug later.

**Comment by nickliqian** [comment]
We already fix this bug~thanks your PR!
