### ISSUE TITLE
关于增加负样本

### ISSUE THREAD

**Issue by ChrisKong93** [nickliqian/cnn_captcha#42]
你好，我想请教一下，应该怎么增加负样本，如果我只训练数字，那么负样本是没有数字的背景还是什么？有没有相关的demo呀

**Comment by nickliqian** [comment]
负样本，一般指你训练好模型之后，进行识别任务的时候识别无法得到正确结果的样本。
此时你可以将这些错误样本标记并放入训练集继续训练，可以提升模型准确率。
