### ISSUE TITLE
关于图片格式的问题

### ISSUE THREAD

**Issue by Crice22** [nickliqian/cnn_captcha#45]
新手一枚，在看到 “2e8j_17322d3d4226f0b5c5a71d797d2ba7f7.jpg格式命名（标签_序列号.后缀）”这里时产生疑问，标签号是图片里的内容，序列号是什么，谢谢

**Comment by zhbzhbzhbz** [comment]
我猜是随机字符串

**Comment by timewalkerF** [comment]
标签号不是验证码识别结果吗。我也没用过，不需要识别结果就能训练吗。

**Comment by zhbzhbzhbz** [comment]
标签号是用来训练的，他问的是序列号

**Comment by nickliqian** [comment]
@Crice22 
@zhbzhbzhbz 是的。
