### ISSUE TITLE
大佬好，请问train_model_v2中输出的字符准确率和图片准确率都代表的是什么？我之前碰到的都是一个准确率的。。。。

### ISSUE THREAD

**Issue by sumiting** [nickliqian/cnn_captcha#46]
[训练集] 字符准确率为 0.98750 图片准确率为 0.95000 >>> loss 0.0152852684
[验证集] 字符准确率为 0.77000 图片准确率为 0.35000 >>> loss 0.0152852684

**Comment by nickliqian** [comment]
假设：有100张图片，每张图片四个字符，共400个字符。我们这里把任务拆分为为需要识别400个字符
字符准确率：识别400的字符中，正确字符的占比。
图片准确率：100张图片中，4个字符完全识别准确的图片占比。

**Comment by sumiting** [comment]
懂了，谢谢大佬------------------ 原始邮件 ------------------
发件人: "Nick Li"<notifications@github.com>
发送时间: 2019年6月1日(星期六) 中午11:50
收件人: "nickliqian/cnn_captcha"<cnn_captcha@noreply.github.com>;
抄送: "sumiting"<1150169485@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [nickliqian/cnn_captcha] 大佬好，请问train_model_v2中输出的字符准确率和图片准确率都代表的是什么？我之前碰到的都是一个准确率的。。。。 (#46)



假设：有100张图片，每张图片四个字符，共400个字符。我们这里把任务拆分为为需要识别400个字符
 字符准确率：识别400的字符中，正确字符的占比。
 图片准确率：100张图片中，4个字符完全识别准确的图片占比。
 
&mdash;
