### ISSUE TITLE
from sample import sample_conf  一直报错

### ISSUE THREAD

**Issue by yanshaoyun** [nickliqian/cnn_captcha#48]

**Comment by yanshaoyun** [comment]
无法导入sample模块
是否是python版本问题
python3.5
tensorflow1.7

**Comment by yanshaoyun** [comment]
Testing started at 21:29 ...
C:\Users\YSY\AppData\Local\Continuum\anaconda3\envs\py35gpu\python.exe "C:\Program Files\JetBrains\PyCharm 2019.1.2\helpers\pycharm\_jb_pytest_runner.py" --path C:/Users/YSY/PycharmProjects/验证码/cnn_captcha-master/ttest_batch.py
Launching pytest with arguments C:/Users/YSY/PycharmProjects/验证码/cnn_captcha-master/ttest_batch.py in C:\Users\YSY\PycharmProjects\验证码\cnn_captcha-master
============================= test session starts =============================
platform win32 -- Python 3.5.6, pytest-3.8.1, py-1.6.0, pluggy-0.11.0
rootdir: C:\Users\YSY\PycharmProjects\验证码\cnn_captcha-master, inifile:collected 0 items

============================== warnings summary ===============================
C:\Users\YSY\AppData\Local\Continuum\anaconda3\envs\py35gpu\lib\site-packages\tensorflow\python\framework\ops.py:875: DeprecationWarning: builtin type EagerTensor has no __module__ attribute
  EagerTensor = c_api.TFE_Py_InitEagerTensor(_EagerTensorBase)

C:\Users\YSY\AppData\Local\Continuum\anaconda3\envs\py35gpu\lib\site-packages\tensorflow\python\util\tf_inspect.py:45: DeprecationWarning: inspect.getargspec() is deprecated, use inspect.signature() instead
  if d.decorator_argspec is not None), _inspect.getargspec(target))
C:\Users\YSY\AppData\Local\Continuum\anaconda3\envs\py35gpu\lib\site-packages\tensorflow\python\util\tf_inspect.py:45: DeprecationWarning: inspect.getargspec() is deprecated, use inspect.signature() instead
  if d.decorator_argspec is not None), _inspect.getargspec(target))
C:\Users\YSY\AppData\Local\Continuum\anaconda3\envs\py35gpu\lib\site-packages\tensorflow\python\util\tf_inspect.py:45: DeprecationWarning: inspect.getargspec() is deprecated, use inspect.signature() instead
  if d.decorator_argspec is not None), _inspect.getargspec(target))
C:\Users\YSY\AppData\Local\Continuum\anaconda3\envs\py35gpu\lib\site-packages\tensorflow\python\util\tf_inspect.py:45: DeprecationWarning: inspect.getargspec() is deprecated, use inspect.signature() instead
  if d.decorator_argspec is not None), _inspect.getargspec(target))
C:\Users\YSY\AppData\Local\Continuum\anaconda3\envs\py35gpu\lib\site-packages\tensorflow\python\util\tf_inspect.py:45: DeprecationWarning: inspect.getargspec() is deprecated, use inspect.signature() instead
  if d.decorator_argspec is not None), _inspect.getargspec(target))
C:\Users\YSY\AppData\Local\Continuum\anaconda3\envs\py35gpu\lib\site-packages\tensorflow\python\util\tf_inspect.py:45: DeprecationWarning: inspect.getargspec() is deprecated, use inspect.signature() instead
  if d.decorator_argspec is not None), _inspect.getargspec(target))
C:\Users\YSY\AppData\Local\Continuum\anaconda3\envs\py35gpu\lib\site-packages\tensorflow\python\util\tf_inspect.py:45: DeprecationWarning: inspect.getargspec() is deprecated, use inspect.signature() instead
  if d.decorator_argspec is not None), _inspect.getargspec(target))
C:\Users\YSY\AppData\Local\Continuum\anaconda3\envs\py35gpu\lib\site-packages\tensorflow\python\util\tf_inspect.py:45: DeprecationWarning: inspect.getargspec() is deprecated, use inspect.signature() instead
  if d.decorator_argspec is not None), _inspect.getargspec(target))
C:\Users\YSY\AppData\Local\Continuum\anaconda3\envs\py35gpu\lib\site-packages\tensorflow\python\util\tf_inspect.py:45: DeprecationWarning: inspect.getargspec() is deprecated, use inspect.signature() instead
  if d.decorator_argspec is not None), _inspect.getargspec(target))
C:\Users\YSY\AppData\Local\Continuum\anaconda3\envs\py35gpu\lib\site-packages\tensorflow\python\util\tf_inspect.py:45: DeprecationWarning: inspect.getargspec() is deprecated, use inspect.signature() instead
  if d.decorator_argspec is not None), _inspect.getargspec(target))
C:\Users\YSY\AppData\Local\Continuum\anaconda3\envs\py35gpu\lib\site-packages\tensorflow\python\util\tf_inspect.py:45: DeprecationWarning: inspect.getargspec() is deprecated, use inspect.signature() instead
  if d.decorator_argspec is not None), _inspect.getargspec(target))
C:\Users\YSY\AppData\Local\Continuum\anaconda3\envs\py35gpu\lib\site-packages\tensorflow\python\util\tf_inspect.py:45: DeprecationWarning: inspect.getargspec() is deprecated, use inspect.signature() instead
  if d.decorator_argspec is not None), _inspect.getargspec(target))
C:\Users\YSY\AppData\Local\Continuum\anaconda3\envs\py35gpu\lib\site-packages\tensorflow\python\util\tf_inspect.py:45: DeprecationWarning: inspect.getargspec() is deprecated, use inspect.signature() instead
  if d.decorator_argspec is not None), _inspect.getargspec(target))
C:\Users\YSY\AppData\Local\Continuum\anaconda3\envs\py35gpu\lib\site-packages\tensorflow\python\util\tf_inspect.py:45: DeprecationWarning: inspect.getargspec() is deprecated, use inspect.signature() instead
  if d.decorator_argspec is not None), _inspect.getargspec(target))
C:\Users\YSY\AppData\Local\Continuum\anaconda3\envs\py35gpu\lib\site-packages\tensorflow\python\util\tf_inspect.py:45: DeprecationWarning: inspect.getargspec() is deprecated, use inspect.signature() instead
  if d.decorator_argspec is not None), _inspect.getargspec(target))
C:\Users\YSY\AppData\Local\Continuum\anaconda3\envs\py35gpu\lib\site-packages\tensorflow\python\util\tf_inspect.py:45: DeprecationWarning: inspect.getargspec() is deprecated, use inspect.signature() instead
  if d.decorator_argspec is not None), _inspect.getargspec(target))
C:\Users\YSY\AppData\Local\Continuum\anaconda3\envs\py35gpu\lib\site-packages\tensorflow\python\util\tf_inspect.py:45: DeprecationWarning: inspect.getargspec() is deprecated, use inspect.signature() instead
  if d.decorator_argspec is not None), _inspect.getargspec(target))
C:\Users\YSY\AppData\Local\Continuum\anaconda3\envs\py35gpu\lib\site-packages\tensorflow\python\util\tf_inspect.py:45: DeprecationWarning: inspect.getargspec() is deprecated, use inspect.signature() instead
  if d.decorator_argspec is not None), _inspect.getargspec(target))
C:\Users\YSY\AppData\Local\Continuum\anaconda3\envs\py35gpu\lib\site-packages\tensorflow\python\util\tf_inspect.py:45: DeprecationWarning: inspect.getargspec() is deprecated, use inspect.signature() instead
  if d.decorator_argspec is not None), _inspect.getargspec(target))
C:\Users\YSY\AppData\Local\Continuum\anaconda3\envs\py35gpu\lib\site-packages\tensorflow\python\util\tf_inspect.py:45: DeprecationWarning: inspect.getargspec() is deprecated, use inspect.signature() instead
  if d.decorator_argspec is not None), _inspect.getargspec(target))
C:\Users\YSY\AppData\Local\Continuum\anaconda3\envs\py35gpu\lib\site-packages\tensorflow\python\util\tf_inspect.py:45: DeprecationWarning: inspect.getargspec() is deprecated, use inspect.signature() instead
  if d.decorator_argspec is not None), _inspect.getargspec(target))

C:\Users\YSY\PycharmProjects\验证码\cnn_captcha-master\ttest_batch.py:11: PytestWarning: cannot collect test class 'TestError' because it has a __init__ constructor
  class TestError(Exception):

C:\Users\YSY\PycharmProjects\验证码\cnn_captcha-master\ttest_batch.py:15: PytestWarning: cannot collect test class 'TestBatch' because it has a __init__ constructor
  class TestBatch(object):

-- Docs: https://docs.pytest.org/en/latest/warnings.html

**Comment by yanshaoyun** [comment]
问题好像是这个no tests were found

**Comment by wardseptember** [comment]
把根目录设置为source root
