### ISSUE TITLE
验证集图片准确率20%左右，训练集准确率98%左右，是否哪里要优化？

### ISSUE THREAD

**Issue by wardseptember** [nickliqian/cnn_captcha#49]
验证集图片准确率20%左右，训练集准确率99%左右，是否哪里要优化？
刚跑了2000张验证码，验证码网址为[http://beian.miit.gov.cn/icp/publish/query/icpMemoInfo_showPage.action#](url)
验证集准确率有点跑不上去了。

**Comment by nickliqian** [comment]
验证码图片的数量增加上去试试
