### ISSUE TITLE
请问一下纯数字但是长度不一致的验证码识别率高吗

### ISSUE THREAD

**Issue by timewalkerF** [nickliqian/cnn_captcha#50]
网站是https://worldwide.espacenet.com/captchaChallengeGenerator?rnd=1

![image](https://user-images.githubusercontent.com/30802962/58469297-c94c0200-8171-11e9-92e3-6350ff29f12c.png)

这种验证码可以通过这个识别吗

**Comment by wardseptember** [comment]
这个项目现在不能识别长度不定的验证码
