### ISSUE TITLE
执行test_batch报错

### ISSUE THREAD

**Issue by zcj13556856559** [nickliqian/cnn_captcha#51]
File "E:\anaconda\lib\site-packages\tensorflow\python\training\saver.py", line 1312, in restore
    err, "a mismatch between the current graph and the graph")

InvalidArgumentError: Restoring from checkpoint failed. This is most likely due to a mismatch between the current graph and the graph from the checkpoint. Please ensure that you have not altered the graph expected based on the checkpoint. Original error:

Assign requires shapes of both tensors to match. lhs shape= [13312,1024] rhs shape= [23040,1024]
	 [[node save/Assign_9 (defined at C:/Users/1/.spyder-py3/captcha/test_batch.py:161) ]]

**Comment by wardseptember** [comment]
可能是你的python、TensorFlow版本不太对，或者重新下载整个项目。

**Comment by zcj13556856559** [comment]
我的python是3.7、TensorFlow是1.13.1，请问我应该如何搭配这两个版本

**Comment by zcj13556856559** [comment]
> 可能是你的python、TensorFlow版本不太对，或者重新下载整个项目。

我的python是3.7、TensorFlow是1.13.1，请问我应该如何搭配这两个版本

**Comment by nickliqian** [comment]
看上去是你的训练集所训练出来的模型和验证集里面的图片大小不一致，请检查一下。
