### ISSUE TITLE
怎么区分验证码是否为不同种类

### ISSUE THREAD

**Issue by vanche1212** [nickliqian/cnn_captcha#52]
市面上的英数4位验证码有好多种，我训练其中一种之后，用很相似的另一种验证码（宽高一样）去识别，准确率很低诶，有没有方案去解决啊，大侠

**Comment by vanche1212** [comment]
不同的程序产生的4位英数验证码就是不同的类吗，都需要训练过啊？那我登录网站页面的验证码都是没有class_label的，是要自己去手动识别，再作为训练集吗？

**Comment by nickliqian** [comment]
1. 不同验证码训练的模型，由于泛化能力弱，识别其他验证码的准确率会很低（对程序来说的相似，和你所认为的相似是不一样的）
2. 解决泛化能力弱的办法，目前只能是增加对应样本，让程序学到更多不同验证码图片的特征
3. 你登陆网站的的验证码图片的标签，需要自己标记或者在打码平台标记
