### ISSUE TITLE
关于验证码数量的问题

### ISSUE THREAD

**Issue by fireflydong** [nickliqian/cnn_captcha#54]
如果训练集有一万张的话，训练一次是一万张都训练吗，还是随机抽取多少张训练呀，验证的时候是什么情况呢，希望大佬不吝赐教

**Comment by nickliqian** [comment]
【如果训练集有一万张的话，训练一次是一万张都训练吗，还是随机抽取多少张训练呀】  
训练一次取的图片和`sample_config.json`中的`train_batch_size`参数有关，目前默认是128张，是先将所有图片排序好，然后依次按照顺序循环取出图片训练。  
【验证的时候是什么情况呢】  
每次验证的图片数量和`sample_config.json`中的`test_batch_size`参数有关，目前默认是100张。  
验证的时候是随机从验证集里面取的100张。
