### ISSUE TITLE
请问这个方法适用如下的验证码图片吗

### ISSUE THREAD

**Issue by xautzxc** [nickliqian/cnn_captcha#56]
![0dk0_num16](https://user-images.githubusercontent.com/30285313/59739118-24b37080-9296-11e9-9199-5df1f4bf3b8d.jpg)
![0m4u_num21](https://user-images.githubusercontent.com/30285313/59739120-254c0700-9296-11e9-9795-a692ae794499.jpg)
![0mo1_num22](https://user-images.githubusercontent.com/30285313/59739121-254c0700-9296-11e9-802c-9ef5602ac349.jpg)
![0o44_num24](https://user-images.githubusercontent.com/30285313/59739122-25e49d80-9296-11e9-919d-f68d9f3c703d.jpg)
我的origin数量一共1076张，根据verify_and_split_data.py自动分成train和test数据。配置参数如下：  "image_width": 65,
  "image_height": 25,
  "max_captcha": 4,
  "image_suffix": "jpg",
  "char_set": "0123456789abcdefghijklmnopqrstuvwxyz",
  "use_labels_json_file": false,
  "remote_url": "http://127.0.0.1:6100/captcha/",
  "cycle_stop": 20000,
  "acc_stop": 0.99,
  "cycle_save": 500,
  "enable_gpu": 0
问题：图片准确率低

第19970次训练 >>> 
[训练集] 字符准确率为 0.33500 图片准确率为 0.03000 >>> loss 0.0000869953
[验证集] 字符准确率为 0.38000 图片准确率为 0.01000 >>> loss 0.0000869953
第19980次训练 >>> 
[训练集] 字符准确率为 0.35000 图片准确率为 0.03000 >>> loss 0.0001388737
[验证集] 字符准确率为 0.42000 图片准确率为 0.04000 >>> loss 0.0001388737
第19990次训练 >>> 
[训练集] 字符准确率为 0.36000 图片准确率为 0.01000 >>> loss 0.0000536628
[验证集] 字符准确率为 0.34750 图片准确率为 0.00000 >>> loss 0.0000536628
第20000次训练 >>> 
[训练集] 字符准确率为 0.36500 图片准确率为 0.02000 >>> loss 0.0000577325
[验证集] 字符准确率为 0.41000 图片准确率为 0.03000 >>> loss 0.0000577325

**Comment by nickliqian** [comment]
请增加样本的数量，一千有点少 @xautzxc

**Comment by nickliqian** [comment]
这种样本是可以训练的

**Comment by xautzxc** [comment]
您的意思是增加样本数量，有希望提高图片准确率是吗？我的原图只有65*25大小，这个对结果有影响吗？我试了将图变成灰度，然后三次样条插值成100*60，20000次训练结果跟原图差不多（如上所示的准确率）。

**Comment by LydiaCai1203** [comment]
> 您的意思是增加样本数量，有希望提高图片准确率是吗？我的原图只有65_25大小，这个对结果有影响吗？我试了将图变成灰度，然后三次样条插值成100_60，20000次训练结果跟原图差不多（如上所示的准确率）。

我训练了将近100k次 "max_captcha": 5 目前的训练集字符准确率在95%上下浮动

**Comment by LydiaCai1203** [comment]
训练了近300k次，max_captcha：5 的验证码的图片，验证集的字符准确率大概在60%上下浮动，图片准确率在10%上下浮动....然后 再训练，正确率就上不去了........

**Comment by xautzxc** [comment]
> 训练了近300k次，max_captcha：5 的验证码的图片，验证集的字符准确率大概在60%上下浮动，图片准确率在10%上下浮动....然后 再训练，正确率就上不去了........

你的验证码图片类型跟我的相似的吗，300k次，emmm...花了多少时间

**Comment by nickliqian** [comment]
@LydiaCai1203 你有多少张样本，另外你的图片是什么样的

**Comment by nickliqian** [comment]
@xautzxc 是的，增加样本量和增加负样本
