### ISSUE TITLE
pip install tensorflow==1.7.0 不存在

### ISSUE THREAD

**Issue by o1dcat** [nickliqian/cnn_captcha#57]
在CentOS7上安装tensorflow==1.7.0时报错如下：
(cnnCAPTCHAenv370) [root@localhost cnn_captcha-1.0]# pip install tensorflow==1.7.0
Collecting tensorflow==1.7.0
  ERROR: Could not find a version that satisfies the requirement tensorflow==1.7.0 (from versions: 1.13.0rc1, 1.13.0rc2, 1.13.1, 1.14.0rc0, 1.14.0rc1, 1.14.0, 2.0.0a0, 2.0.0b0, 2.0.0b1)
ERROR: No matching distribution found for tensorflow==1.7.0
(cnnCAPTCHAenv370) [root@localhost cnn_captcha-1.0]#

而安装最新tensorflow==1.14.0后，需要大量的依赖升级，涉及到gcc++,glibc++,make......几乎底层C库要全部升一遍。docker封装好的tensorflow版本是否可以用呢？

**Comment by nickliqian** [comment]
请问你的pip默认是python2还是python3呢，是32位还是64位，这个是对tf的安装有影响的
另外可以使用docker封装好的环境，没有什么区别。

**Comment by o1dcat** [comment]
感谢回答。我是Python3.7.0的，安装在centos7上的64位的系统。现在试着用docker了。

**Comment by MEGALO-JOE** [comment]
安装最新版本的是否会有影响？

**Comment by nickliqian** [comment]
@MEGALO-JOE 影响不大，但是请尽量使用和项目对应的版本
