### ISSUE TITLE
训练 测试都正常，为什么启动recognize_api.py时会出错？

### ISSUE THREAD

**Issue by crack521** [nickliqian/cnn_captcha#6]
![image](https://user-images.githubusercontent.com/7234477/48963919-b268ff00-efd8-11e8-8413-6231575a65de.png)

**Comment by nickliqian** [comment]
检查一下你的脚本启动路径、模型文件的保存路径是否正常。同时请提供更多的消息：系统版本、目录结构、测试结果等

**Comment by crack521** [comment]
感谢及时回复！应该是相对路径 那个recognize_api.py 没有识别出来，我把sample.py里面的model路径 改成绝对路径就可以了。【训练时相对路径可以 测试也行 就是api调用时相对路径出错了】
