### ISSUE TITLE
有关模型h5文件怎么生成的?

### ISSUE THREAD

**Issue by jjeejj** [nickliqian/cnn_captcha#62]

**Comment by jjeejj** [comment]
有关模型h5文件怎么生成的?  新手，现在只想要训练好的h5模型文件

**Comment by nickliqian** [comment]
试着参考这篇博客：[tensorflow 模型权重导出至h5文件](https://blog.csdn.net/zhongxing9006/article/details/80898830)  
把你的model目录下的模型导出为h5格式
