### ISSUE TITLE
直接clone的代码，里面有训练过的模型吗?再起flask服务的时候会报错。

### ISSUE THREAD

**Issue by ZhangYiBo513** [nickliqian/cnn_captcha#64]
### 报错内容：File ".\webserver_recognize_api.py", line 13, in <module>
                          from cnnlib.recognition_object import Recognizer
                          File "C:\Users\venndata\Desktop\cnn_captcha\cnnlib\recognition_object.py", line 13, in <module>
                         from conf.sample import sample_conf
                         ModuleNotFoundError: No module named 'conf.sample'

**Comment by vivitsai** [comment]
我也是这样的报错~

**Comment by ZhangYiBo513** [comment]
这是配置文件读取有问题，你看下recognition_object这个文件的16行，读取配置文件

**Comment by vivitsai** [comment]
> 这是配置文件读取有问题，你看下recognition_object这个文件的16行，读取配置文件

具体是哪行有问题啊 怎么解决？

**Comment by ZhangYiBo513** [comment]
![aa](https://user-images.githubusercontent.com/38456466/60782246-7dc94280-a178-11e9-96c8-affbf9615102.PNG)
就是这样解决的

**Comment by nickliqian** [comment]
@ZhangYiBo513 非常感谢，正解
@vivitsai 此问题已经修复，请更新最新代码运行
