### ISSUE TITLE
我从目标网站下载了好多验证码，但是不知道标签，一定要手动输入标签才能训练吗？

### ISSUE THREAD

**Issue by ZhangYiBo513** [nickliqian/cnn_captcha#66]

**Comment by Fizzyi** [comment]
应该是的 不然程序怎么知道是否识别正确

**Comment by xiangbei1997** [comment]
可以根据自己的需求然后你自己生成你想要的验证码格式,然后跟他格式一样就可以用了

**Comment by ZhangYiBo513** [comment]
但是我不知道对方网站采用什么方式生成的验证码。。。

**Comment by ZhangYiBo513** [comment]
![111](https://user-images.githubusercontent.com/38456466/60783050-6fc8f100-a17b-11e9-8bd7-97ec98dfa792.jpg)
就是这种可以用python生成吗?

**Comment by nickliqian** [comment]
@ZhangYiBo513 
1. 手动输入标签或者使用打码平台打标签
2. 你使用脚本生成的验证码，由于参数不一定一致，所以不一定能识别目标验证码
3. 如果你需要打标签，可以把通过邮件的形式把验证码发给我。

**Comment by xiangbei1997** [comment]
抱歉,因为最近在研究实体命名的问题,为看到邮件
--以上文件是我自定义生成的验证码,你可以加根据自己的需求修改

**Comment by xiangbei1997** [comment]
这是生成的的,格式,  代码里面charlist = ['heiti.ttf', 'songti.ttf', 'lishu.ttf']表示的是字体

**Comment by ZhangYiBo513** [comment]
为什么我没有从项目里，找到这个charlist这个参数呢？在哪个文件呢？


------------------ 原始邮件 ------------------
发件人: "xiangbei1997"<notifications@github.com>;
发送时间: 2019年7月19日(星期五) 上午8:43
收件人: "nickliqian/cnn_captcha"<cnn_captcha@noreply.github.com>;
抄送: "单只鸳鸯"<1057964760@qq.com>;"Mention"<mention@noreply.github.com>;
主题: Re: [nickliqian/cnn_captcha] 我从目标网站下载了好多验证码，但是不知道标签，一定要手动输入标签才能训练吗？ (#66)



这是生成的的,格式,  代码里面charlist = ['heiti.ttf', 'songti.ttf', 'lishu.ttf']表示的是字体

**Comment by xiangbei1997** [comment]
这个我刚刚给你发的是我自己写的文件，并不是源码带的


在 2019-07-19 11:16:54，"ZhangYiBo513" <notifications@github.com> 写道：
为什么我没有从项目里，找到这个charlist这个参数呢？在哪个文件呢？


------------------ 原始邮件 ------------------
发件人: "xiangbei1997"<notifications@github.com>;
发送时间: 2019年7月19日(星期五) 上午8:43
收件人: "nickliqian/cnn_captcha"<cnn_captcha@noreply.github.com>;
抄送: "单只鸳鸯"<1057964760@qq.com>;"Mention"<mention@noreply.github.com>;
主题: Re: [nickliqian/cnn_captcha] 我从目标网站下载了好多验证码，但是不知道标签，一定要手动输入标签才能训练吗？ (#66)



这是生成的的,格式, 代码里面charlist = ['heiti.ttf', 'songti.ttf', 'lishu.ttf']表示的是字体
