### ISSUE TITLE
太多报错了

### ISSUE THREAD

**Issue by zhushichuan** [nickliqian/cnn_captcha#71]
![image](https://user-images.githubusercontent.com/27287970/61204583-2733a980-a720-11e9-9b11-183709c33e78.png)
![image](https://user-images.githubusercontent.com/27287970/61204595-31ee3e80-a720-11e9-9b50-e01137e10512.png)

**Comment by jerry94test** [comment]
你仔细看文档

**Comment by jerry94test** [comment]
我感觉他这个 写的很全了就是不咋准 我跑了 3w轮了
