### ISSUE TITLE
一直提示一个错误

### ISSUE THREAD

**Issue by zhushichuan** [nickliqian/cnn_captcha#73]
Hint: If you want to see a list of allocated tensors when OOM happens, add report_tensor_allocations_upon_oom to RunOptions for current allocation info.

大哥怎么解决的呀

**Comment by nickliqian** [comment]
看上去是内存不够导致  
你运行的时候有运行其他任务吗？  
如果没有，可以尝试修改batch_size的大小。

**Comment by nickliqian** [comment]
@zhushichuan 
更新代码：
新增`sample_config.json`中的`train_batch_size`参数，如果发生OMM可以尝试减小此参数。

**Comment by Funny-dot** [comment]
已解决  是gpu的错误，windows上没安装gpu  配置文件是gpu  改为cpu训练模式就行了
