### ISSUE TITLE
修改图片默认尺寸之后，训练效果大打折扣

### ISSUE THREAD

**Issue by l976308589** [nickliqian/cnn_captcha#74]
使用gen_sample_by_captcha生成数据，宽乘以高=203*66，字符个数为6，默认4.
图片数量为5k，当前运行了60k次
[训练集] 字符准确率为 1 图片准确率为 1 
[验证集] 字符准确率为 0.45000 图片准确率为 0.01000
请问是什么原因，可以优化吗？

**Comment by nickliqian** [comment]
增加训练集的样本数量，继续训练，可以提高准确率。
