### ISSUE TITLE
二次训练

### ISSUE THREAD

**Issue by Aaaronchen** [nickliqian/cnn_captcha#78]
怎么进行二次训练呢，不知是不是我的操作有误，导致图片正确率一度下降，增加训练集是否需要删除原训练集，不需要删除的话，二次训练是否有记忆在原来的基础上只训练增加集

**Comment by nickliqian** [comment]
进行二次训练：后续有了更多的样本，可以把样本放在new_image_dir目录中再次执行verify_and_split_data  
增加训练集是否需要删除原训练集：不需要删除  
二次训练是否有记忆在原来的基础上只训练增加集：二次训练是在之前的模型基础上优化模型能力
