### ISSUE TITLE
大佬，这种情况需要人工停止吗？

### ISSUE THREAD

**Issue by kingking888** [nickliqian/cnn_captcha#80]
第610次训练 >>> 
[训练集] 字符准确率为 1.00000 图片准确率为 1.00000 >>> loss 0.0129696298
[验证集] 字符准确率为 0.00000 图片准确率为 0.00000 >>> loss 0.0129696298
第620次训练 >>> 
[训练集] 字符准确率为 1.00000 图片准确率为 1.00000 >>> loss 0.0114498623
[验证集] 字符准确率为 0.00000 图片准确率为 0.00000 >>> loss 0.0114498623

**Comment by nickliqian** [comment]
继续训练吧~
