### ISSUE TITLE
（修改图片大小后导致训练会出现问题）麻烦请补上验证码生成大小的问题

### ISSUE THREAD

**Issue by fqdeng** [nickliqian/cnn_captcha#86]
![image](https://user-images.githubusercontent.com/21285645/63908013-2052c300-ca50-11e9-8a94-1ee572cd1377.png)

**Comment by fqdeng** [comment]
![image](https://user-images.githubusercontent.com/21285645/63908037-382a4700-ca50-11e9-87b0-d0b924a4dfa4.png)

**Comment by bao17634** [comment]
怎么样 你的这个问题解决了吗

**Comment by fqdeng** [comment]
> 怎么样 你的这个问题解决了吗

自己手动加上就好了
